server:
  port: ${coride.server.port}

spring:
  profiles:
    active: ${coride.spring.profiles.active}
  main:
    allow-circular-references: ${coride.spring.main.allow-circular-references}
  datasource:
    druid:
      driver-class-name: ${coride.datasource.driver-class-name}
      url: jdbc:mysql://${coride.datasource.host}:${coride.datasource.port}/${coride.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${coride.datasource.username}
      password: ${coride.datasource.password}
  redis:
    host: ${coride.redis.host}
    port: ${coride.redis.port}
    password: ${coride.redis.password}
    database: ${coride.redis.database}
    lettuce:
      pool:
        max-active: ${coride.redis.lettuce.pool.max-active}
        min-idle: ${coride.redis.lettuce.pool.min-idle}
        max-idle: ${coride.redis.lettuce.pool.max-idle}
        max-wait: ${coride.redis.lettuce.pool.max-wait}

  cloud:
    nacos:
      discovery:
        server-addr: ${coride.nacos.discovery.server-addr}
        service: ${coride.nacos.discovery.service}

  rabbitmq:
    host: ${coride.rabbitmq.host}
    port: ${coride.rabbitmq.port}
    virtual-host: ${coride.rabbitmq.virtual-host}
    username: ${coride.rabbitmq.username}
    password: ${coride.rabbitmq.password}

  mail:
    host: ${coride.mail.host}
    username: ${coride.mail.username}
    password: ${coride.mail.password}
    default-encoding: ${coride.mail.default-encoding}
    protocol: ${coride.mail.protocol}
    properties:
      mail:
        smtp:
          auth: ${coride.mail.smtp.auth}
          starttls:
            enabled: ${coride.mail.smtp.starttls.enabled}
            required: ${coride.mail.smtp.starttls.required}

mybatis:
  mapper-locations: ${coride.mybatis.mapper-locations}
  type-aliases-package: ${coride.mybatis.type-aliases-package}
  configuration:
    map-underscore-to-camel-case: ${coride.mybatis.map-underscore-to-camel-case}

logging:
  level:
    com:
      coride:
        mapper: ${coride.logging.level.mapper}
        service: ${coride.logging.level.service}
        controller: ${coride.logging.level.controller}

coride:
  jwt:
    admin-secret-key: ${coride.jwt.admin-secret-key}
    admin-ttl: ${coride.jwt.admin-ttl}
    admin-token-name: ${coride.jwt.admin-token-name}
    excludedPath: ${coride.jwt.excludedPath}

  alioss:
    endpoint: ${coride.alioss.endpoint}
    access-key-id: ${coride.alioss.access-key-id}
    access-key-secret: ${coride.alioss.access-key-secret}
    bucket-name: ${coride.alioss.bucket-name}

  threadpool:
    corePoolSize: ${coride.threadpool.corePoolSize:5}         # 核心线程数，默认值为5
    maxPoolSize: ${coride.threadpool.maxPoolSize:20}         # 最大线程数，默认值为20
    queueCapacity: ${coride.threadpool.queueCapacity:100}    # 阻塞队列容量，默认值为100
    keepAliveTime: ${coride.threadpool.keepAliveTime:30}     # 非核心线程存活时间（秒），默认值为30
