version: '3.9'

services:

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

  nacos:
    image: nacos/nacos-server:2.0.2
    container_name: nacos
    environment:
      MODE: standalone
      NACOS_AUTH_ENABLE: false
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: host.docker.internal
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root123
    ports:
      - "8848:8848"
    networks:
      - app_network

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123    # root 用户密码（你可以改）
      MYSQL_DATABASE: nacos_config    # 启动时自动建库
      MYSQL_USER: nacos               # 额外创建的 nacos 用户
      MYSQL_PASSWORD: nacos123        # nacos 用户密码
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql       # 持久化数据
      - ./mysql/init:/docker-entrypoint-initdb.d
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

networks:
  app_network:
    driver: bridge